services:
  hugo:
    image: hugomods/hugo:exts
    command: hugo server --bind 0.0.0.0 --navigateToChanged
    volumes:
      - ".:/src"
      - "${DOCS_PATH}:/src/content/docs"
      - "${WORK_PATH}:/src/content/work"
      - "${RECIPES_PATH}:/src/content/recipes"
    ports:
      - 1313:1313
    restart: unless-stopped
